# Site settings
title: "Ashutosh Mohan"
description: "Programming Projects & Writing"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ashutosh Mohan"
resume_title:                   "Generalist looking to "

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ashutoshmohan@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 9791172335"
resume_contact_address:         " "

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>
I am a generalist with strong problem solving and analytical stills. I’ve worked as a part of founding engineering teams at two Accel-funded startups where I translated a business problems into tech solutions, iterating quickly to release a product, and evolving a small engineering team of typically <5 members around it. I’ve built web and mobile apps (including an AR app) and bootstrapped products ranging from e-commerce platforms, gamification and simulation to tools to explore dynamical systems. I am looking for projects where I can be contribute to the early development of exciting product ideas. 
<br>

I've also breifly dabbled as a film writer contributing to Film Companion South where I was part of the editorial team. Link to <a href="https://www.filmcompanion.in/author/ashutoshmohangmail-com/"> author page </a>. 

The following is a brief overview of projects I've worked on. Here's a <a href="https://github.com/notashutosh/notashutosh.github.io/blob/gh-pages/CV%20Ashutosh%20Mohan.pdf"> detailed resume </a>. 

</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/notashutosh"
  resume_twitter_url:           "http://twitter.com/notashutosh"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ashutosh-mohan-142295b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://notashutosh.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
